services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: TCPServer
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  server:
    build: .
    ports:
      - "4124:4124"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PG_HOST: db
      PG_PORT: 5432
    volumes:
      - ./logs:/app/logs

volumes:
  pg_data: